language: ruby
cache: bundler
rvm:
 - "2.3.1"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec
addons:
  postgresql: "9.4"
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
