default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: stoperica

test:
  <<: *default
  database: mtb_test

production:
  <<: *default
  database: mtb_production
  username: mtb_timing
  password: <%= ENV['MTB_TIMING _DATABASE_PASSWORD'] %>
