default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mtb_development

test:
  <<: *default
  database: mtb_test

production:
  <<: *default
  database: mtb_production
  username: mtb_timinf
  password: <%= ENV['MTB_TIMING_DATABASE_PASSWORD'] %>
