default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: amrood123

development:
  <<: *default
  database: stoperica

test:
  <<: *default
  database: mtb_test

production:
  <<: *default
  database: stoperica
  username: rails
  password: <%= ENV['EXAMPLE_DATABASE_PASSWORD'] %>
